#!/bin/sh
# Build the SYNTHETIC fixtures — the machine shapes the developer does not own.
#
# READ THIS BEFORE TRUSTING THEM.
#
# A synthetic fixture proves that the code handles the attribute SHAPE the kernel documentation
# describes. It is NOT evidence about a real AMD, ARM or acpi-cpufreq machine, because nobody has
# run this on one. Every value below is either quoted from the kernel documentation under
# Documentation/admin-guide/pm/ (cpufreq.rst, intel_pstate.rst, amd-pstate.rst) or is an
# obviously-plausible number chosen to exercise a code path; none of it was measured.
#
# Each generated directory carries a README that says all of this, so the marking cannot be lost
# by copying the directory somewhere else. When somebody DOES capture one of these shapes from
# real hardware with scripts/capture-sysfs.sh, it replaces the synthetic one and the README
# changes from SYNTHETIC to REAL.
#
# Usage:  scripts/make-synthetic-fixtures.sh [output-root]     (default: tests/fixtures)

set -eu

root=${1:-tests/fixtures}

# put <fixture> <relative-path> <value>
put() {
    mkdir -p "$root/$1/devices/system/cpu/$(dirname "$2")"
    printf '%s\n' "$3" > "$root/$1/devices/system/cpu/$2"
}

# policy <fixture> <n> <driver> <governors> <governor> <minkhz> <maxkhz> <curkhz>
policy() {
    _f=$1; _n=$2; _drv=$3; _govs=$4; _gov=$5; _min=$6; _max=$7; _cur=$8
    put "$_f" "cpufreq/policy$_n/scaling_driver"              "$_drv"
    put "$_f" "cpufreq/policy$_n/scaling_available_governors" "$_govs"
    put "$_f" "cpufreq/policy$_n/scaling_governor"            "$_gov"
    put "$_f" "cpufreq/policy$_n/affected_cpus"               "$_n"
    put "$_f" "cpufreq/policy$_n/related_cpus"                "$_n"
    put "$_f" "cpufreq/policy$_n/cpuinfo_min_freq"            "$_min"
    put "$_f" "cpufreq/policy$_n/cpuinfo_max_freq"            "$_max"
    put "$_f" "cpufreq/policy$_n/scaling_min_freq"            "$_min"
    put "$_f" "cpufreq/policy$_n/scaling_max_freq"            "$_max"
    put "$_f" "cpufreq/policy$_n/scaling_cur_freq"            "$_cur"
    put "$_f" "cpufreq/policy$_n/cpuinfo_transition_latency"  "0"
}

# epp <fixture> <n> <current>
epp() {
    put "$1" "cpufreq/policy$2/energy_performance_available_preferences" \
        "default performance balance_performance balance_power power"
    put "$1" "cpufreq/policy$2/energy_performance_preference" "$3"
}

# idlestate <fixture> <cpu> <m> <name> <latency-us> <residency-us> <desc>
#
# One entry of the kernel's cpuidle array. This is a DIFFERENT SUBSYSTEM from everything else in
# this script: cpufreq is how fast a core runs, cpuidle is what it does when it has nothing to do
# and what it costs to wake it. DAW mode lives entirely here, and it resolves its PM-QoS limit by
# probing these files, so a fixture with no cpuidle tree cannot exercise it at all.
#
# The kernel guarantees these mean the same thing everywhere -- "idle states [...] are represented
# in an abstract way independent of the platform or the processor architecture" (cpuidle.rst:
# 125-131) -- which is why the probe has no architecture in it and neither do these tables beyond
# their state NAMES, which are display-only.
#
# The latencies below are PLAUSIBLE, NOT MEASURED, exactly like every other number in this file.
# What they are chosen to exercise is stated at each call site.
idlestate() {
    _f=$1; _c=$2; _m=$3; _nm=$4; _lat=$5; _res=$6; _desc=$7
    put "$_f" "cpu$_c/cpuidle/state$_m/name"      "$_nm"
    put "$_f" "cpu$_c/cpuidle/state$_m/latency"   "$_lat"
    put "$_f" "cpu$_c/cpuidle/state$_m/residency" "$_res"
    put "$_f" "cpu$_c/cpuidle/state$_m/desc"      "$_desc"
    put "$_f" "cpu$_c/cpuidle/state$_m/disable"   "0"
}

readme() {
    _f=$1; _title=$2; _why=$3; _shape=$4
    cat > "$root/$_f/README.md" <<EOF
# Fixture: $_f

$_title

## ⚠ SYNTHETIC — NOT EVIDENCE ABOUT A REAL MACHINE

Generated by \`scripts/make-synthetic-fixtures.sh\`. **Nobody has run this tool on hardware of
this shape.** Every value here is either quoted from the kernel's `Documentation/admin-guide/pm/`
documentation or is a plausible number chosen to exercise a code path.
None of it was measured.

What this fixture *does* prove: the model handles the attribute **shape** the kernel documentation
describes for this driver — which attributes exist, which do not, and what the code resolves the
five slider stops to as a result.

What it does **not** prove: that a real machine of this kind behaves this way.

**Replace it.** Run \`scripts/capture-sysfs.sh\` on real hardware of this shape and commit the
result over the top; the README then becomes REAL.

$_why

## Shape

\`\`\`
$_shape
\`\`\`
EOF
}

# ---------------------------------------------------------------------------------------------
# acpi-cpufreq — the classic generic interface. The full governor set and NO EPP, so this is the
# fixture where the five stops must be separated by GOVERNOR rather than by energy hint. It is the
# mirror image of the development machine and therefore the most important synthetic one.
# Global boost knob: "This file is located under /sys/devices/system/cpu/cpufreq/" (cpufreq.rst).
# ---------------------------------------------------------------------------------------------
f=acpi-cpufreq
rm -rf "$root/$f"
G="conservative ondemand userspace powersave performance schedutil"
for n in 0 1 2 3; do
    policy "$f" "$n" acpi-cpufreq "$G" ondemand 800000 3800000 2200000
    put "$f" "cpufreq/policy$n/scaling_available_frequencies" "3800000 3400000 2800000 2200000 1600000 800000"
done
put "$f" present 0-3
put "$f" online  0-3
put "$f" cpufreq/boost 1
# acpi_idle's classic ACPI C-state table. Exercises the ordinary case: a POLL pseudo-state at 0,
# then a cheap halt, then states too expensive for an audio period. DAW mode must resolve to 1 --
# C1 -- and NOT to 0, which would admit only POLL and spin all four cores.
for n in 0 1 2 3; do
    idlestate "$f" "$n" 0 POLL 0   0    "CPUIDLE CORE POLL IDLE"
    idlestate "$f" "$n" 1 C1   1   1    "ACPI FFH MWAIT 0x0"
    idlestate "$f" "$n" 2 C2   104 400  "ACPI IOPORT 0x414"
    idlestate "$f" "$n" 3 C3   350 1000 "ACPI IOPORT 0x415"
done
readme "$f" \
  "A quad-core x86 machine on the generic \`acpi-cpufreq\` driver: the full governor set, **no EPP**, and the global \`cpufreq/boost\` knob." \
  "This is the mirror image of the development machine, and the reason it matters most: here the
five stops are separated by **governor**, where on \`intel_pstate\` they are separated by **EPP**.
If the preference table in \`src/core/profile.cpp\` is wrong, this is the fixture that shows it." \
"driver     acpi-cpufreq
policies   4
governors  $G
epp        ABSENT
turbo      cpufreq/boost (global, not inverted)
freq       800 MHz - 3.80 GHz, 6 discrete steps
idle       POLL 0us, C1 1us, C2 104us, C3 350us   -> DAW mode limit 1us (C1)"

# ---------------------------------------------------------------------------------------------
# amd-pstate-epp — AMD's active mode. Same two-governor shape as intel_pstate active, so the stops
# are separated by EPP again; but the turbo knob is PER-POLICY, not global and not inverted:
#   "users can write a value of `0` to disable the boost or `1` to enable it, for the respective
#    CPU using the sysfs path `/sys/devices/system/cpu/cpuX/cpufreq/boost`"  -- amd-pstate.rst:349
# ---------------------------------------------------------------------------------------------
f=amd-pstate-epp
rm -rf "$root/$f"
for n in 0 1 2 3 4 5 6 7; do
    policy "$f" "$n" amd-pstate-epp "performance powersave" powersave 400000 5200000 3000000
    epp "$f" "$n" balance_performance
    put "$f" "cpufreq/policy$n/boost" 1
done
put "$f" present 0-7
put "$f" online  0-7
put "$f" amd_pstate/status active
# Same shape as the acpi-cpufreq table and for the same reason: the C-state names differ from
# Intel's but the array does not, so the probe must not care. Resolves to 1.
for n in 0 1 2 3 4 5 6 7; do
    idlestate "$f" "$n" 0 POLL 0   0    "CPUIDLE CORE POLL IDLE"
    idlestate "$f" "$n" 1 C1   1   2    "ACPI FFH MWAIT 0x0"
    idlestate "$f" "$n" 2 C2   350 800  "ACPI IOPORT 0x414"
done
put "$f" amd_pstate/prefcore enabled
readme "$f" \
  "An AMD machine with \`amd-pstate-epp\` in **active** mode: two governors plus EPP, and a **per-policy** boost knob." \
  "This is the fixture that exercises the per-policy turbo path. \`intel_pstate\` has a single
global \`no_turbo\` (inverted); this driver has one \`boost\` file per policy (not inverted), so the
plan must contain one turbo write per policy rather than one for the machine." \
"driver     amd-pstate-epp
policies   8
governors  performance powersave
epp        default performance balance_performance balance_power power
mode       amd_pstate/status = active
turbo      policyN/boost (per-policy, NOT inverted)
freq       400 MHz - 5.20 GHz
idle       POLL 0us, C1 1us, C2 350us            -> DAW mode limit 1us (C1)"

# ---------------------------------------------------------------------------------------------
# amd-pstate-passive — the same hardware in passive mode: generic governors are back and EPP is
# gone, so the stops are separated by governor again. amd_pstate has FOUR modes, not three:
#   "Operation mode of the driver: "active", "passive", "guided" or "disable"" -- amd-pstate.rst:501
# ---------------------------------------------------------------------------------------------
f=amd-pstate-passive
rm -rf "$root/$f"
for n in 0 1 2 3 4 5 6 7; do
    policy "$f" "$n" amd-pstate "$G" schedutil 400000 5200000 2800000
    put "$f" "cpufreq/policy$n/boost" 1
done
put "$f" present 0-7
put "$f" online  0-7
put "$f" amd_pstate/status passive
# The SAME hardware as amd-pstate-epp, so the same idle table. cpuidle is not affected by the
# cpufreq driver's mode at all, and this fixture pair is what says so: the stops resolve
# differently between the two, DAW mode resolves identically.
for n in 0 1 2 3 4 5 6 7; do
    idlestate "$f" "$n" 0 POLL 0   0    "CPUIDLE CORE POLL IDLE"
    idlestate "$f" "$n" 1 C1   1   2    "ACPI FFH MWAIT 0x0"
    idlestate "$f" "$n" 2 C2   350 800  "ACPI IOPORT 0x414"
done
readme "$f" \
  "The same AMD machine with \`amd-pstate\` in **passive** mode: generic governors, **no EPP**, per-policy boost." \
  "Passive mode is where a driver that had EPP loses it. This fixture proves the capability probe
follows the machine rather than the driver name — the driver string still begins \`amd-pstate\`,
but there is no energy hint to write, and the stops must fall back to governor differentiation." \
"driver     amd-pstate
policies   8
governors  $G
epp        ABSENT (passive mode)
mode       amd_pstate/status = passive
turbo      policyN/boost (per-policy, NOT inverted)
freq       400 MHz - 5.20 GHz
idle       POLL 0us, C1 1us, C2 350us            -> DAW mode limit 1us (C1)"

# ---------------------------------------------------------------------------------------------
# cppc-arm — an ARM server with NO turbo knob of any kind, and several CPUs sharing one policy.
# Both are shapes the x86 fixtures cannot produce, and both must degrade rather than fail: the
# Turbo checkbox is disabled and labelled, never silently ignored.
# ---------------------------------------------------------------------------------------------
f=cppc-arm
rm -rf "$root/$f"
n=0
for cpus in "0-3" "4-7"; do
    policy "$f" "$n" cppc_cpufreq "$G" schedutil 1000000 2600000 1800000
    put "$f" "cpufreq/policy$n/affected_cpus" "$(echo "$cpus" | tr '-' ' ' | { read a b; s=""; i=$a; while [ "$i" -le "$b" ]; do s="$s $i"; i=$((i+1)); done; echo "$s" | sed 's/^ //'; })"
    put "$f" "cpufreq/policy$n/related_cpus"  "$(cat "$root/$f/devices/system/cpu/cpufreq/policy$n/affected_cpus")"
    n=$((n+4))
done
put "$f" present 0-7
put "$f" online  0-7
# TWO SHAPES NO x86 FIXTURE CAN PRODUCE, and both are the point of this table.
#
# First: there is NO POLL STATE. ARM's PSCI idle driver starts at WFI, which really halts, so the
# shallowest state here has a NON-ZERO exit latency. A tool that writes a hardcoded 0 to
# /dev/cpu_dma_latency leaves this machine unable to enter ANY state -- not even WFI -- and the
# cores fall into the idle loop's spin (cpuidle.rst:107-109). This fixture is what proves the
# limit is probed rather than assumed.
#
# Second: the clusters are HETEROGENEOUS. cpus 0-3 are the little cluster and 4-7 the big one,
# and they publish different tables -- which real big.LITTLE hardware does. The limit is a single
# GLOBAL number, so it must be the MAXIMUM over each CPU's shallowest halt state (3, the big
# cluster's WFI) and not the minimum (1): at 1 the big cluster has no admissible state at all and
# spins. Taking cpu0's table alone would make exactly that mistake.
for n in 0 1 2 3; do
    idlestate "$f" "$n" 0 WFI             1   1    "ARM WFI"
    idlestate "$f" "$n" 1 cpu-sleep       40  100  "ARM cpu-sleep-0"
    idlestate "$f" "$n" 2 cluster-sleep   500 1500 "ARM cluster-sleep-0"
done
for n in 4 5 6 7; do
    idlestate "$f" "$n" 0 WFI             3   3    "ARM WFI"
    idlestate "$f" "$n" 1 cpu-sleep       75  200  "ARM cpu-sleep-1"
    idlestate "$f" "$n" 2 cluster-sleep   800 2500 "ARM cluster-sleep-1"
done
readme "$f" \
  "An ARM server on \`cppc_cpufreq\`: **no turbo knob at all**, and **four CPUs share each policy**. Policy indices are non-contiguous (0 and 4)." \
  "Two shapes no x86 fixture can produce. First, a machine with no boost/turbo attribute anywhere:
the Turbo checkbox must be **disabled and labelled**, and the plan must carry a note saying why —
never a control that looks live and does nothing. Second, policies that do not map one-to-one onto
CPUs and whose indices are **not contiguous**, which is what stops the model from ever assuming
policy N drives CPU N.

It carries two more that belong to **cpuidle** rather than cpufreq. There is **no POLL state** —
ARM starts at WFI, which really halts — so a hardcoded PM-QoS limit of 0 would admit *nothing* and
leave every core in the idle loop's spin. And the two clusters publish **different idle tables**,
so the single global limit has to be the maximum over each CPU's shallowest halting state rather
than the minimum, or the big cluster spins while the little one sleeps." \
"driver     cppc_cpufreq
policies   2  (policy0 -> cpus 0-3, policy4 -> cpus 4-7)
governors  $G
epp        ABSENT
turbo      ABSENT  (no no_turbo, no boost, no cpb)
freq       1.00 - 2.60 GHz
idle       NO POLL STATE, and heterogeneous:
             cpu0-3  WFI 1us, cpu-sleep 40us, cluster-sleep 500us
             cpu4-7  WFI 3us, cpu-sleep 75us, cluster-sleep 800us
           -> DAW mode limit 3us, the MAX of the two clusters' WFI, so
              neither cluster is left spinning"

echo "synthetic fixtures written under $root:"
for d in acpi-cpufreq amd-pstate-epp amd-pstate-passive cppc-arm; do
    printf "  %-22s %3s attributes\n" "$d" "$(find "$root/$d" -type f ! -name README.md | wc -l)"
done
