// coretest — the offline gate for src/core/.
//
// For every fixture, every slider stop and both turbo states, this renders the EXACT ORDERED
// WritePlan and compares it against a committed golden file.
//
// WHY A GOLDEN FILE. Three of the kernel's constraints on this interface are ordering constraints
// rather than value constraints, so a plan containing the right writes in the wrong order is a
// plan that silently half-applies. Asserting the rendered order makes any change to it a change
// that has to be explained. A failing golden is a claim that the tool's behaviour changed; it is
// answered by saying what changed and why, NEVER by re-running --update to make it green.
//
// WHY FIXTURES. The developer has one machine and this tool claims to work on all of them. Each
// fixture is a captured (or, where marked, documented) sysfs tree, and pointing Sysfs at one is
// transparent: the tree beneath is identical to /sys, so nothing else in the model changes.
//
// Usage:
//   coretest                 run every check; exit 0 if all pass, 1 otherwise
//   coretest --update        rewrite the golden files (deliberate act; read the diff first)
//   coretest --print <fix>   dump one fixture's plans to stdout

#include "../src/core/backend.h"
#include "../src/core/profile.h"
#include "../src/core/idle.h"
#include "../src/core/sysfs.h"
#include "../src/core/topology.h"

#include <cstdio>
#include <cstring>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

using namespace cpupower;

namespace
{

const char *kFixtureDir = "tests/fixtures";
const char *kGoldenDir = "tests/golden";

const std::vector<std::string> kFixtures = {
    "intel-pstate-active-hwp", // REAL, this machine
    "acpi-cpufreq",            // synthetic
    "amd-pstate-epp",          // synthetic
    "amd-pstate-passive",      // synthetic
    "cppc-arm",                // synthetic
};

int gChecks = 0;
int gFailures = 0;

void fail(const std::string &what)
{
    ++gFailures;
    std::cout << "  FAIL  " << what << "\n";
}

// Returns the result so a caller can skip the checks that only make sense once this one held --
// reporting five consequential failures for one cause makes the count say more than it knows.
bool check(bool ok, const std::string &what)
{
    ++gChecks;
    if (!ok)
        fail(what);
    return ok;
}

//------------------------------------------------------------------------
// The full rendering for one fixture: the probed backend, then every stop x turbo combination.
std::string renderFixture(const std::string &fixture)
{
    const Sysfs fs(std::string(kFixtureDir) + "/" + fixture);
    const Backend backend = Backend::probe(fs);

    std::ostringstream o;
    o << "# " << fixture << "\n";
    o << "# Generated by tools/coretest. Do not edit by hand.\n";
    o << "\n";
    o << "backend:  " << backend.describe() << "\n";
    o << "driver:   " << (backend.driver.empty() ? "(none)" : backend.driver) << "\n";
    o << "mode:     " << (backend.modeText.empty() ? "(n/a)" : backend.modeText) << "\n";
    o << "usable:   " << (backend.usable() ? "yes" : "no") << "\n";
    if (!backend.usable())
        o << "reason:   " << backend.unusableReason() << "\n";

    o << "policies: " << backend.policies.size() << " [";
    for (size_t i = 0; i < backend.policies.size(); ++i)
        o << (i ? " " : "") << backend.policies[i].index;
    o << "]\n";

    o << "govs:     ";
    for (size_t i = 0; i < backend.governors.size(); ++i)
        o << (i ? " " : "") << backend.governors[i];
    o << "\n";

    o << "epp:      ";
    if (backend.eppChoices.empty())
        o << "(none)";
    else
        for (size_t i = 0; i < backend.eppChoices.size(); ++i)
            o << (i ? " " : "") << backend.eppChoices[i];
    o << "\n";

    o << "turbo:    " << turboKnobName(backend.turbo)
      << (backend.turboInverted() ? " (inverted)" : "")
      << (backend.turboPerPolicy() ? " (per-policy)" : "") << "\n";
    o << "perf_pct: " << (backend.hasPerfPct ? "yes" : "no") << "\n";

    for (int s = 0; s < kStopCount; ++s) {
        const Stop stop = static_cast<Stop>(s);
        for (int t = 1; t >= 0; --t) {
            Request req;
            req.stop = stop;
            req.turbo = (t != 0);
            req.touchTurbo = true;

            o << "\n=== " << stopKey(stop) << " turbo=" << (t ? "on" : "off") << " ===\n";
            o << buildPlan(fs, backend, req).dump();
        }
    }

    return o.str();
}

//------------------------------------------------------------------------
std::string readFile(const std::string &path)
{
    std::ifstream in(path, std::ios::binary);
    if (!in)
        return {};
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

bool writeFile(const std::string &path, const std::string &text)
{
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    if (!out)
        return false;
    out << text;
    return out.good();
}

//------------------------------------------------------------------------
// Show the first differing line, with context. A whole-file diff of a 200-line golden is not
// something anyone reads; the first divergence is what you actually need.
void reportDiff(const std::string &got, const std::string &want)
{
    std::istringstream g(got), w(want);
    std::string gl, wl;
    int line = 0;
    while (true) {
        const bool gok = static_cast<bool>(std::getline(g, gl));
        const bool wok = static_cast<bool>(std::getline(w, wl));
        ++line;
        if (!gok && !wok)
            break;
        if (gl != wl) {
            std::cout << "        first difference at line " << line << ":\n";
            std::cout << "          golden: " << (wok ? wl : "(end of file)") << "\n";
            std::cout << "          actual: " << (gok ? gl : "(end of file)") << "\n";
            return;
        }
        if (!gok || !wok)
            break;
    }
}

//------------------------------------------------------------------------
void testGoldens(bool update)
{
    for (const std::string &fixture : kFixtures) {
        const std::string golden = std::string(kGoldenDir) + "/" + fixture + ".txt";
        const std::string got = renderFixture(fixture);

        if (update) {
            if (writeFile(golden, got))
                std::cout << "  updated  " << golden << "\n";
            else
                fail("could not write " + golden);
            continue;
        }

        const std::string want = readFile(golden);
        ++gChecks;
        if (want.empty()) {
            ++gFailures;
            std::cout << "  FAIL  " << fixture << ": golden file missing or empty (" << golden
                      << ")\n";
        } else if (got != want) {
            ++gFailures;
            std::cout << "  FAIL  " << fixture << ": plan differs from golden\n";
            reportDiff(got, want);
        } else {
            std::cout << "  ok    " << fixture << "\n";
        }
    }
}

//------------------------------------------------------------------------
// Properties that must hold on EVERY fixture, whatever its shape. These are the invariants the
// golden files cannot express, because a golden only says "this is what happened", not "this is
// what must always be true".
void testInvariants()
{
    for (const std::string &fixture : kFixtures) {
        const Sysfs fs(std::string(kFixtureDir) + "/" + fixture);
        const Backend backend = Backend::probe(fs);
        const std::string at = " [" + fixture + "]";

        check(backend.usable(), "fixture should be usable" + at);

        // Policy indices must be strictly ascending. listDirs sorts as strings, where policy10
        // precedes policy9, so this is a real thing to get wrong.
        for (size_t i = 1; i < backend.policies.size(); ++i) {
            check(backend.policies[i - 1].index < backend.policies[i].index,
                  "policy indices ascending" + at);
        }

        for (int s = 0; s < kStopCount; ++s) {
            const Stop stop = static_cast<Stop>(s);
            Request req;
            req.stop = stop;
            req.turbo = true;
            const WritePlan plan = buildPlan(fs, backend, req);
            const std::string what = std::string(" [") + fixture + " " + stopKey(stop) + "]";

            // ORDERING RULE 1 (intel_pstate.rst:130-133): the EPP write is rejected while the
            // governor is `performance`. So every EPP write must come AFTER every governor write.
            // This is the constraint most likely to be broken by a well-meaning refactor, and it
            // fails silently on hardware, so it is asserted structurally here.
            long lastGovernor = -1;
            long firstEpp = -1;
            for (size_t i = 0; i < plan.writes.size(); ++i) {
                const std::string &p = plan.writes[i].path;
                if (p.find("scaling_governor") != std::string::npos)
                    lastGovernor = static_cast<long>(i);
                if (p.find("energy_performance_preference") != std::string::npos && firstEpp < 0)
                    firstEpp = static_cast<long>(i);
            }
            if (firstEpp >= 0) {
                check(lastGovernor >= 0 && firstEpp > lastGovernor,
                      "every EPP write follows every governor write" + what);
            }

            // The Maximum stop selects the `performance` governor, under which the driver forces
            // EPP and rejects any write. So Maximum must never emit one.
            if (stop == Stop::Maximum && plan.resolvedGovernor == "performance") {
                check(firstEpp < 0, "Maximum must not attempt an EPP write" + what);
            }

            // Turbo is the frequency envelope the governor then works within, so it goes first.
            long firstGovernor = -1;
            long lastTurbo = -1;
            for (size_t i = 0; i < plan.writes.size(); ++i) {
                const std::string &p = plan.writes[i].path;
                if (p.find("scaling_governor") != std::string::npos && firstGovernor < 0)
                    firstGovernor = static_cast<long>(i);
                if (p.find("no_turbo") != std::string::npos ||
                    p.find("/boost") != std::string::npos || p.find("/cpb") != std::string::npos)
                    lastTurbo = static_cast<long>(i);
            }
            if (lastTurbo >= 0 && firstGovernor >= 0)
                check(lastTurbo < firstGovernor, "turbo writes precede governor writes" + what);

            // A governor or EPP we emit must be one the kernel told us it accepts. This is the
            // rule that makes the tool work on hardware nobody here owns.
            for (const Write &w : plan.writes) {
                if (w.path.find("scaling_governor") != std::string::npos)
                    check(backend.supports(w.value),
                          "governor \"" + w.value + "\" is in the kernel's own list" + what);
                if (w.path.find("energy_performance_preference") != std::string::npos)
                    check(backend.supportsEpp(w.value),
                          "EPP \"" + w.value + "\" is in the kernel's own list" + what);
            }

            // Every policy is covered, or none is. A governor applied to some CPUs and not others
            // is the silent half-apply this whole layer exists to prevent.
            size_t govWrites = 0;
            for (const Write &w : plan.writes) {
                if (w.path.find("scaling_governor") != std::string::npos)
                    ++govWrites;
            }
            check(govWrites == backend.policies.size(), "one governor write per policy" + what);
        }

        // Turbo must be honoured or explained, never silently dropped.
        {
            Request req;
            req.stop = Stop::Maximum;
            req.turbo = false;
            req.touchTurbo = true;
            const WritePlan plan = buildPlan(fs, backend, req);
            size_t turboWrites = 0;
            for (const Write &w : plan.writes) {
                if (w.path.find("no_turbo") != std::string::npos ||
                    w.path.find("/boost") != std::string::npos ||
                    w.path.find("/cpb") != std::string::npos)
                    ++turboWrites;
            }
            if (backend.turbo == TurboKnob::None) {
                check(turboWrites == 0 && !plan.notes.empty(),
                      "a machine with no turbo knob says so in a note" + at);
            } else if (backend.turboPerPolicy()) {
                check(turboWrites == backend.policies.size(),
                      "per-policy turbo writes one file per policy" + at);
            } else {
                check(turboWrites == 1, "global turbo writes exactly one file" + at);
            }
        }
    }

    // The inversion must be resolved in exactly one place, and it must actually invert. On
    // intel_pstate, "turbo on" means writing 0 to no_turbo.
    {
        const Sysfs fs(std::string(kFixtureDir) + "/intel-pstate-active-hwp");
        const Backend backend = Backend::probe(fs);
        check(backend.turboInverted(), "intel_pstate no_turbo is flagged inverted");

        for (int t = 0; t <= 1; ++t) {
            Request req;
            req.stop = Stop::Maximum;
            req.turbo = (t != 0);
            const WritePlan plan = buildPlan(fs, backend, req);
            for (const Write &w : plan.writes) {
                if (w.path.find("no_turbo") != std::string::npos) {
                    const std::string expect = t ? "0" : "1";
                    check(w.value == expect, std::string("turbo=") + (t ? "on" : "off") +
                                                 " writes no_turbo=" + expect + ", got \"" +
                                                 w.value + "\"");
                }
            }
        }

        // ... and NOT inverted on the AMD fixture, where boost=1 means boost on.
        const Sysfs fs2(std::string(kFixtureDir) + "/amd-pstate-epp");
        const Backend b2 = Backend::probe(fs2);
        check(!b2.turboInverted(), "amd-pstate boost is not inverted");
        Request req;
        req.stop = Stop::Maximum;
        req.turbo = true;
        for (const Write &w : buildPlan(fs2, b2, req).writes) {
            if (w.path.find("/boost") != std::string::npos)
                check(w.value == "1", "turbo=on writes boost=1 on amd-pstate");
        }
    }

    // The five stops must be DISTINCT where the hardware allows it. On the two fixtures with a
    // rich enough vocabulary, all five must resolve differently; a table that collapses them is a
    // slider with fewer positions than it draws.
    for (const char *fixture : {"intel-pstate-active-hwp", "acpi-cpufreq"}) {
        const Sysfs fs(std::string(kFixtureDir) + "/" + fixture);
        const Backend backend = Backend::probe(fs);
        std::vector<std::string> seen;
        for (int s = 0; s < kStopCount; ++s) {
            Request req;
            req.stop = static_cast<Stop>(s);
            const WritePlan plan = buildPlan(fs, backend, req);
            seen.push_back(plan.resolvedGovernor + "/" + plan.resolvedEpp);
        }
        for (size_t i = 0; i < seen.size(); ++i) {
            for (size_t j = i + 1; j < seen.size(); ++j) {
                check(seen[i] != seen[j], std::string("stops ") + stopKey(static_cast<Stop>(i)) +
                                              " and " + stopKey(static_cast<Stop>(j)) +
                                              " resolve differently [" + fixture + "]");
            }
        }
    }
}

//------------------------------------------------------------------------
// DAW mode's PM-QoS limit, which is cpuidle and not cpufreq.
//
// This is asserted as its own section because the goldens cannot cover it: a WritePlan is a list
// of sysfs writes, and DAW mode makes none -- it holds /dev/cpu_dma_latency open, which is the
// only way to make a PM-QoS constraint stick and the only way to release it
// (pm_qos_interface.rst). So the tested artefact here is THE NUMBER THE PROBE RESOLVES TO.
//
// The invariant that matters, and the bug this replaced: the limit must never be a value under
// which some CPU has no idle state it can enter. The governors "should never select any idle
// states with exit latency beyond that limit" (cpuidle.rst:577-581), and a CPU left with nothing
// selectable does not idle -- it spins (cpuidle.rst:107-109), burning power and heat on every
// core. Writing a hardcoded 0 does exactly that on every machine, because POLL is the only
// zero-latency state anywhere.
void testIdle()
{
    struct Expect {
        const char *fixture;
        long long limitUs;
        const char *admitted;
    };

    // Each expectation is a claim about that fixture's SHAPE, not about a real machine of that
    // kind -- see the README in each synthetic fixture directory.
    static const Expect kExpect[] = {
        {"intel-pstate-active-hwp", 2, "C1E"}, // REAL: POLL 0, C1E 2, C6 220, C8 280, C10 680
        {"acpi-cpufreq", 1, "C1"},             // POLL 0, C1 1, C2 104, C3 350
        {"amd-pstate-epp", 1, "C1"},           // POLL 0, C1 1, C2 350
        {"amd-pstate-passive", 1, "C1"},       // the same hardware: cpufreq mode cannot move this
        // No POLL state at all, and two clusters with different tables. 3, not 1: 1 is the little
        // cluster's WFI, and at 1 the big cluster (WFI 3) has nothing it may enter.
        {"cppc-arm", 3, "WFI"},
    };

    for (const Expect &e : kExpect) {
        const Sysfs fs(std::string(kFixtureDir) + "/" + e.fixture);
        const IdleStates idle = IdleStates::probe(fs);
        const std::string at = std::string(" [") + e.fixture + "]";

        check(idle.present, "fixture exposes cpuidle" + at);
        if (!check(idle.limitUs.has_value(), "a DAW mode limit resolves" + at))
            continue;

        check(*idle.limitUs == e.limitUs, "DAW limit is " + std::to_string(e.limitUs) + "us, got " +
                                              std::to_string(*idle.limitUs) + at);

        // Never 0. That is the whole point, so it is asserted separately from the exact value:
        // if somebody changes the resolution rule, this line still catches the spin loop.
        check(*idle.limitUs > 0, "DAW limit is never 0, which would admit only POLL" + at);

        const IdleStates::State *a = idle.admitted();
        check(a != nullptr && a->name == e.admitted,
              std::string("deepest admitted state is ") + e.admitted + at);

        // Heterogeneity is a display fact, not a policy one, but it must be detected: on such a
        // machine `states` is one CPU's table and the limit can be a number that is not in it.
        const bool expectHetero = (std::string(e.fixture) == "cppc-arm");
        check(idle.heterogeneous == expectHetero,
              std::string("heterogeneous is ") + (expectHetero ? "set" : "clear") + at);

        // EVERY CPU must keep a state it can halt in, which is what makes the aggregation a
        // maximum over CPUs rather than cpu0's answer. On the heterogeneous fixture these differ.
        for (int cpu = 0; cpu < 64; ++cpu) {
            const std::string dir =
                std::string("devices/system/cpu/cpu") + std::to_string(cpu) + "/cpuidle";
            if (fs.listDirs(dir).empty())
                continue;

            bool canHalt = false;
            for (const std::string &st : fs.listDirs(dir)) {
                const std::optional<long long> lat = fs.readInt(dir + "/" + st + "/latency");
                if (lat && *lat > 0 && *lat <= *idle.limitUs)
                    canHalt = true;
            }
            check(canHalt, "cpu" + std::to_string(cpu) + " has a halting state at the limit" + at);
        }
    }

    // A machine with no cpuidle at all must say so rather than offer a control that does nothing.
    {
        const IdleStates idle = IdleStates::probe(Sysfs("/nonexistent/definitely/not/here"));
        check(!idle.present, "a missing root exposes no cpuidle");
        check(!idle.limitUs.has_value(), "a missing root resolves no DAW limit");
        check(!idle.unavailableReason().empty(), "a missing root explains why DAW mode is off");
    }
}

//------------------------------------------------------------------------
// Hostile and degenerate inputs. None of these may crash, hang, or produce a plan.
void testNegative()
{
    // A root that does not exist at all.
    {
        const Sysfs fs("/nonexistent/definitely/not/here");
        const Backend backend = Backend::probe(fs);
        check(!backend.usable(), "a missing sysfs root is not usable");
        check(!backend.unusableReason().empty(), "a missing root explains itself");
        Request req;
        const WritePlan plan = buildPlan(fs, backend, req);
        check(plan.writes.empty(), "a missing root produces no writes");
        check(!plan.notes.empty(), "a missing root produces a note");
    }

    // A root that exists but has no cpufreq interface (a VM with no scaling driver).
    {
        const Sysfs fs("/tmp");
        const Backend backend = Backend::probe(fs);
        check(!backend.usable(), "a root with no cpufreq is not usable");
        Request req;
        check(buildPlan(fs, backend, req).writes.empty(), "no cpufreq produces no writes");
    }

    // readInt must reject anything that is not a complete integer. "<unsupported>" is the real
    // one -- intel_pstate's scaling_setspeed reads exactly that -- and reading it as 0 would look
    // entirely plausible and be entirely wrong.
    {
        const Sysfs fs(std::string(kFixtureDir) + "/intel-pstate-active-hwp");
        const std::string p = "devices/system/cpu/cpufreq/policy0/";
        check(!fs.readInt(p + "scaling_setspeed").has_value(), "readInt rejects \"<unsupported>\"");
        check(fs.readInt(p + "cpuinfo_max_freq").has_value(), "readInt accepts a real integer");
        check(!fs.readInt(p + "scaling_driver").has_value(), "readInt rejects a driver name");
        check(!fs.readInt("devices/system/cpu/cpufreq/policy0/nope").has_value(),
              "readInt rejects a missing file");
    }

    // parseCpuList must not be trickable into a huge allocation or a wrong answer.
    {
        check(parseCpuList("0-19").size() == 20, "parseCpuList 0-19");
        check(parseCpuList("0,2-4,7").size() == 5, "parseCpuList sparse");
        check(parseCpuList("").empty(), "parseCpuList empty");
        check(parseCpuList("garbage").empty(), "parseCpuList garbage");
        check(parseCpuList("0-999999999").empty(), "parseCpuList refuses a huge range");
        check(parseCpuList("5-1").empty(), "parseCpuList refuses a reversed range");
        check(parseCpuList("-3").empty(), "parseCpuList refuses a leading dash");
        check(parseCpuList("0-3,0-3").size() == 4, "parseCpuList de-duplicates");
    }

    // An unrecognised stop key must be rejected, not defaulted. A config file that has drifted
    // must never silently select a different power level than the one it names.
    {
        Stop s = Stop::Maximum;
        check(!stopFromKey("turbo-max-ultra", s), "an unknown stop key is rejected");
        check(s == Stop::Maximum, "a rejected key leaves the output untouched");
        check(stopFromKey("balanced", s) && s == Stop::Balanced, "a known stop key round-trips");
        for (int i = 0; i < kStopCount; ++i) {
            Stop r;
            check(stopFromKey(stopKey(static_cast<Stop>(i)), r) && r == static_cast<Stop>(i),
                  "every stop key round-trips");
        }
    }
}

} // namespace

//------------------------------------------------------------------------
int main(int argc, char **argv)
{
    bool update = false;

    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--update") == 0) {
            update = true;
        } else if (std::strcmp(argv[i], "--print") == 0 && i + 1 < argc) {
            std::cout << renderFixture(argv[i + 1]);
            return 0;
        } else {
            std::cerr << "usage: coretest [--update] [--print <fixture>]\n";
            return 64;
        }
    }

    std::cout << "== golden plans ==\n";
    testGoldens(update);

    if (!update) {
        std::cout << "== invariants ==\n";
        testInvariants();
        std::cout << "== idle (DAW mode) ==\n";
        testIdle();
        std::cout << "== negative ==\n";
        testNegative();
    }

    std::cout << "\n" << gChecks << " checks, " << gFailures << " failed\n";
    return gFailures == 0 ? 0 : 1;
}
